# 예외처리

## 1. Error와 Exception의 차이

1. **Error**
    1. 작동이 중단될 정도로 Fatal한 오류
    1. 오작동을 하거나 비정상적으로 프로그램이 종료됨
    1. (ex)  메모리 부족, stack overflow
1. **Exception**
    1. 수습 가능한 정도의 오류
    1. (ex) 자바스크립트의 규칙을 벗어난 경우, 자바스크립트 내부에 정의되지 않은 변수나 함수를 참조
    1. 처리방법, try catch 구문

## 1. 비동기 상황에서의 예외처리

1. 비동기
    1. 콜스택에 바로 들어가 실행되지 않고,
    1. 작업 큐에서 대기 했다가
    1. 콜스택이 비면 콜스택으로 들어가 실행됨
1. 문제상황
    1. 예외가 발생하는 시점 !== try가 싸고 있는 시점
    1. try catch 구문으로 예외를 잡을 수가 없음
1. 해결 방안
    1. .then(()=>{}, ()=>{})의 두번째 인자로 들어오는 함수는 rejected가 반환되었을 때 실행된다
    1. Promise 객체를 받은 뒤 .catch(()=>{}) 로 에러를 잡아낸다.
    1. try 안에서 함수를 호출할 때 await 구문과 함께 호출한다

    ```js
    const foo = async () => {}
    // 1. then에 두번째 인자 넣기
    foo().then(()=>{
        console.log("success") // onfulfilled
      }, (e)=>{
        console.log(e) // onRejected
      }
    )
    // 2. .catch() 함수로 받기
    foo().catch((e) => {
      console.error(e);
    });
    // 3. try catch 구문 안에 await 사용하기
    try {
      await foo();
    } catch (e) {
      console.error(e);
    }
    // 4. await과 catch문을 동시에 사용하기
    await foo().catch((e)=>{console.error(e)})
    ```
